<a href="https://colab.research.google.com/github/ImranMajeedMir/IPL-project-Task4/blob/main/vedio_game_sales_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

VIDEO GAME SALES PREDICTION Internship Task by Asterisc Technocrat PVT LTD

In [96]:
import numpy as np
import pandas as pd
# for visualization
import matplotlib.pyplot as plt
import seaborn as sns
# for interactiveness
from ipywidgets import interact
import seaborn as sb

In [97]:
from google.colab import files
uploaded = files.upload()

Saving Video_Games_Sales_as_at_22_Dec_2016.csv to Video_Games_Sales_as_at_22_Dec_2016 (3).csv

In [98]:
df1 = pd.read_csv('Video_Games_Sales_as_at_22_Dec_2016.csv')
df1.head(4)

,Name,Platform,Year_of_Release,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Critic_Score,Critic_Count,User_Score,User_Count,Developer,Rating
0,Wii Sports,Wii,2006.0,Sports,Nintendo,41.36,28.96,3.77,8.45,82.53,76.0,51.0,8,322.0,Nintendo,E
1,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24,NaN,NaN,NaN,NaN,NaN,NaN
2,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.68,12.76,3.79,3.29,35.52,82.0,73.0,8.3,709.0,Nintendo,E
3,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.61,10.93,3.28,2.95,32.77,80.0,73.0,8,192.0,Nintendo,E

In [99]:
print(df1.shape)
print(df1.head(5))

(16719, 16)
                       Name Platform  Year_of_Release         Genre Publisher  \
0                Wii Sports      Wii           2006.0        Sports  Nintendo
1         Super Mario Bros.      NES           1985.0      Platform  Nintendo
2            Mario Kart Wii      Wii           2008.0        Racing  Nintendo
3         Wii Sports Resort      Wii           2009.0        Sports  Nintendo
4  Pokemon Red/Pokemon Blue       GB           1996.0  Role-Playing  Nintendo

   NA_Sales  EU_Sales  JP_Sales  Other_Sales  Global_Sales  Critic_Score  \
0     41.36     28.96      3.77         8.45         82.53          76.0
1     29.08      3.58      6.81         0.77         40.24           NaN
2     15.68     12.76      3.79         3.29         35.52          82.0
3     15.61     10.93      3.28         2.95         32.77          80.0
4     11.27      8.89     10.22         1.00         31.37           NaN

   Critic_Count User_Score  User_Count Developer Rating
0          51.0          8       322.0  Nintendo      E
1           NaN        NaN         NaN       NaN    NaN
2          73.0        8.3       709.0  Nintendo      E
3          73.0          8       192.0  Nintendo      E
4           NaN        NaN         NaN       NaN    NaN

In [134]:
df1.isnull().sum()

Name               0
Platform           0
Year_of_Release    0
Genre              0
Publisher          0
NA_Sales           0
EU_Sales           0
JP_Sales           0
Other_Sales        0
Global_Sales       0
Critic_Score       0
Critic_Count       0
User_Score         0
User_Count         0
Developer          0
Rating             0
dtype: int64

In [100]:
df1['Rating'].value_counts()

E       3991
T       2961
M       1563
E10+    1420
EC         8
K-A        3
RP         3
AO         1
Name: Rating, dtype: int64

In [101]:
df1.isna().sum()

Name                  2
Platform              0
Year_of_Release     269
Genre                 2
Publisher            54
NA_Sales              0
EU_Sales              0
JP_Sales              0
Other_Sales           0
Global_Sales          0
Critic_Score       8582
Critic_Count       8582
User_Score         6704
User_Count         9129
Developer          6623
Rating             6769
dtype: int64

In [102]:
df1 = df1.dropna().reset_index(drop=True)

In [103]:
target = []
for i in df1.columns:
  col = df1[i]
  if type(col[0]) == str:
    target.append(i)
    print(i)

Name
Platform
Genre
Publisher
User_Score
Developer
Rating

In [104]:
from sklearn.preprocessing import LabelEncoder
for i in target:
  encoder = LabelEncoder()
  encoder.fit(list(df1[i]))
  df1[i] = encoder.fit_transform(df1[i])

In [105]:
x = df1.drop('Rating', axis=1)

x

,Name,Platform,Year_of_Release,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Critic_Score,Critic_Count,User_Score,User_Count,Developer
0,4215,12,2006.0,10,160,41.36,28.96,3.77,8.45,82.53,76.0,51.0,72,322.0,771
1,2087,12,2008.0,6,160,15.68,12.76,3.79,3.29,35.52,82.0,73.0,75,709.0,771
2,4217,12,2009.0,10,160,15.61,10.93,3.28,2.95,32.77,80.0,73.0,72,192.0,771
3,2567,2,2006.0,4,160,11.28,9.14,6.50,2.88,29.80,89.0,65.0,77,431.0,771
4,4213,12,2006.0,3,160,13.96,9.18,2.93,2.84,28.92,58.0,41.0,58,129.0,771
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6820,1048,3,2001.0,0,158,0.01,0.00,0.00,0.00,0.01,46.0,4.0,16,21.0,411
6821,2297,3,2002.0,2,146,0.01,0.00,0.00,0.00,0.01,81.0,12.0,80,9.0,260
6822,2194,5,2014.0,0,123,0.00,0.01,0.00,0.00,0.01,80.0,20.0,68,412.0,617
6823,407,5,2011.0,8,53,0.01,0.00,0.00,0.00,0.01,61.0,12.0,50,43.0,99
6824,3094,5,2011.0,11,240,0.00,0.01,0.00,0.00,0.01,60.0,12.0,64,13.0,1011

In [106]:
y = df1.Rating
y

0       1
1       1
2       1
3       1
4       1
       ..
6820    1
6821    4
6822    4
6823    6
6824    2
Name: Rating, Length: 6825, dtype: int64

In [107]:
df1['Rating'].value_counts()

6    2377
1    2082
4    1433
2     930
0       1
3       1
5       1
Name: Rating, dtype: int64

In [108]:
x.isna().sum()

Name               0
Platform           0
Year_of_Release    0
Genre              0
Publisher          0
NA_Sales           0
EU_Sales           0
JP_Sales           0
Other_Sales        0
Global_Sales       0
Critic_Score       0
Critic_Count       0
User_Score         0
User_Count         0
Developer          0
dtype: int64

In [109]:
print(df1.dtypes)

Name                 int64
Platform             int64
Year_of_Release    float64
Genre                int64
Publisher            int64
NA_Sales           float64
EU_Sales           float64
JP_Sales           float64
Other_Sales        float64
Global_Sales       float64
Critic_Score       float64
Critic_Count       float64
User_Score           int64
User_Count         float64
Developer            int64
Rating               int64
dtype: object

In [138]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.25, random_state = 0)

In [139]:
 from sklearn.linear_model import LogisticRegression
model = LogisticRegression(random_state = 42)
model.fit(X_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression(random_state=42)

In [124]:
x.head(10)

,Name,Platform,Year_of_Release,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Critic_Score,Critic_Count,User_Score,User_Count,Developer
0,4215,12,2006.0,10,160,41.36,28.96,3.77,8.45,82.53,76.0,51.0,72,322.0,771
1,2087,12,2008.0,6,160,15.68,12.76,3.79,3.29,35.52,82.0,73.0,75,709.0,771
2,4217,12,2009.0,10,160,15.61,10.93,3.28,2.95,32.77,80.0,73.0,72,192.0,771
3,2567,2,2006.0,4,160,11.28,9.14,6.50,2.88,29.80,89.0,65.0,77,431.0,771
4,4213,12,2006.0,3,160,13.96,9.18,2.93,2.84,28.92,58.0,41.0,58,129.0,771
5,2570,12,2009.0,4,160,14.44,6.94,4.70,2.24,28.32,87.0,80.0,76,594.0,771
6,2086,2,2005.0,6,160,9.71,7.47,4.13,1.90,23.21,91.0,64.0,78,464.0,771
7,4207,12,2007.0,10,160,8.92,8.03,3.60,2.15,22.70,80.0,63.0,69,146.0,771
8,1812,14,2010.0,3,144,15.00,4.89,0.24,1.69,21.81,61.0,45.0,55,106.0,469
9,4208,12,2009.0,10,160,9.01,8.49,2.53,1.77,21.79,80.0,33.0,66,52.0,771

In [125]:
y.tail(15)

6810    6
6811    1
6812    4
6813    6
6814    4
6815    2
6816    1
6817    1
6818    2
6819    1
6820    1
6821    4
6822    4
6823    6
6824    2
Name: Rating, dtype: int64

In [140]:
result = model.predict((np.array([[2570,	12,	2009.0,	4,	160,	14.44,	6.94,	4.70,	2.24,	28.32,	87.0,	80.0,	76,	594.0,	771]])))
print( result)
if result == 1 or result == 2 or result == 4 or result == 6:
  print("customer will buy")
else:
  print("customer will not buy it ")

[4]
customer will buy

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

In [141]:
# lets print the classification report
from sklearn.metrics import classification_report
cr = classification_report(y_test, y_pred)
print(cr)
print("Accuracy of the Model: {0}%".format(accuracy_score(y_test, y_pred)*100))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         1
           1       0.49      0.64      0.55       520
           2       0.10      0.01      0.02       231
           4       0.65      0.29      0.41       357
           5       0.00      0.00      0.00         1
           6       0.44      0.63      0.52       597

    accuracy                           0.48      1707
   macro avg       0.28      0.26      0.25      1707
weighted avg       0.45      0.48      0.44      1707

Accuracy of the Model: 47.6274165202109%

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

**we can increase the accuracy of our system by using feature selection methods like IGR, RFE, chi-Squared etc. The feature selection methods gives us the relevent feature and have high impact on the system and then these these can be used for training and testing due to which our system will give better performance**